layout_spectrum: 0.5636727
typography_spectrum: 0.1693164
color:
  saturation: 0.2993891
  lightness: 0.4270056
  brandStrength: 0.7148961
  rhythmicContrast: 0.07071926
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
name: Reviews
